
BLENDER="C:\Program Files\Blender Foundation\Blender 2.93\blender.exe"
DIST=../dist

all : \
    $(DIST)/factory.pnct \
    $(DIST)/factory.scene \

$(DIST)/factory.scene : factory.blend export-scene.py
    $(BLENDER) --background --python export-scene.py -- "factory.blend:Main" "$(DIST)/factory.scene"

$(DIST)/factory.pnct : factory.blend export-meshes.py
    $(BLENDER) --background --python export-meshes.py -- "factory.blend:Main" "$(DIST)/factory.pnct" 
